### PR TITLE
Simplify with method chaining

### PR DESCRIPTION
**Pull request by cclauss**
https://en.m.wikipedia.org/wiki/Fluent_interface

### CODE REVIEW

**Comment by cvpe** [comment]
I know that, I had hesitated but I think it was more readable like I did.
If you tell me this modification will be very more quick, ok...
I even don't know how to close a patch proposal without committing

**Comment by cvpe** [comment]
Ok, I did it, I sincerely know that I don't know a lot 
You are my "ange gardien"

**Comment by cclauss** [comment]
Understood.  This modification might be marginally faster or require marginally less memory but this PR can be closed.  Is there a “Close” button below?

**Comment by cvpe** [comment]
Sorry, we typed at the same moment

**Comment by cvpe** [comment]
But anyway, did you try my script, and what do you think about it? Not useful?

**Comment by cvpe** [comment]
Why not the same modification proposal for?
def pickerView_numberOfRowsInComponent_(self, cmd, picker_view, component):
    UIPickerView = ObjCInstance(picker_view)
    return(len(UIPickerView.assets))

**Comment by cvpe** [comment]
Done

**Pull request merged**
