### PR TITLE
Simplify with str.startswith()

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cvpe** [comment]
I don't agree with your code, please try this. there are 2 cases when you code is not ok

Of course, I could be wrong, in this case sorry...

def my_or_ccc(urlin):
	t = 'https://forum.omz-software.com/topic/'
	url=urlin
	if url:
		if url[:len(t)] != t:
			url = None
	print('my ',urlin,url)
	url = urlin
	if not url:
		url = 'https://forum.omz-software.com/topic/3317/introduction'
	if not url.startswith(t):
		url = t + '3317/introduction'
	print('ccc',urlin,url)
	
my_or_ccc(None)
my_or_ccc('https://forum.omz-software.com/topic/xxxxxx')
my_or_ccc('http://google')

**Comment by cvpe** [comment]
Correction

def my_or_ccc(urlin):
	t = 'https://forum.omz-software.com/topic/'
	url=urlin
	if url:
		if url[:len(t)] != t:
			url = None
	print('my ',urlin,url)
	if not url:
		url = 'https://forum.omz-software.com/topic/3317/introduction'
	url = urlin
	if not url.startswith(t):
		url = t + '3317/introduction'
	print('ccc',urlin,url)
	
my_or_ccc(None)
my_or_ccc('https://forum.omz-software.com/topic/xxxxxx')
my_or_ccc('http://google')

**Comment by cvpe** [comment]
Re-sorry (I just come back from the restaurant)

Correction 2

def my_or_ccc(urlin):
	t = 'https://forum.omz-software.com/topic/'
	url=urlin
	if url:
		if url[:len(t)] != t:
			url = None
	if not url:
		url = 'https://forum.omz-software.com/topic/3317/introduction'
	print('my ',urlin,url)
	url = urlin
	if not url.startswith(t):
		url = t + '3317/introduction'
	print('ccc',urlin,url)
	
my_or_ccc(None)
my_or_ccc('https://forum.omz-software.com/topic/xxxxxx')
my_or_ccc('http://google')

**Comment by cvpe** [comment]
Could you change your request into

	if not url or not url.startswith(t):
		url = t + '3317/introduction'

Thanks and sorry for previous corrections under wine effect

**Comment by cclauss** [comment]
Last piece of the puzzle is that __clipboard.get()__ _always_ returns a str and _never_ returns None.

**Comment by cvpe** [comment]
so please excuse me 😢

**Comment by cclauss** [comment]
LOL... Just having fun!

**Pull request merged**
