### PR TITLE
Add missing comma

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cvpe** [comment]
Sorry but my Pythonista code does not have these lines, thus I suppose I uploaded in the past a bad version but I'm very surprised 
I'll replace the module

**Comment by cclauss** [comment]
https://travis-ci.com/cvpe/Pythonista-scripts/pull_requests
* Travis build number 3 showed me that here was a comma missing
* Travis build number 4 showed me that adding the comma fixed that problem but also highlighted a __print__ problem
* Travis build number 5 showed me that using print function fixed that file completely.

**Comment by cclauss** [comment]
Resolved conflict.

**Comment by cvpe** [comment]
I don't understand, as usual. I've replaced the module by my one and all modifications come as pull requests...

**Comment by cclauss** [comment]
Search on “print “ to see if there are old style __print__statements that need to be converted to __print()__ function.

**Comment by cvpe** [comment]
No one

**Comment by cclauss** [comment]
Fixed.

**Comment by cvpe** [comment]
Thanks

**Pull request closed without merging**
