### PR TITLE
Simplify with sum()

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cvpe** [comment]
Sorry, I've never used these commits... except accepting your modifications because I'm entirely confident and that I don't want to retest the code.
What do I have to do with this conflict?

**Comment by cvpe** [comment]
Why there is a conflict?

**Comment by cvpe** [comment]
I don't understand why there was a conflict but I have resolved the conflict manually, hoping it is ok so

**Comment by cclauss** [comment]
Conflicts arise when two or more pull requests modify the same line(s).  The system wants manual verification that the changes do not create errors.

**Comment by cvpe** [comment]
Thanks for the explanation

**Pull request merged**
