### PR TITLE
Simplify the logic with dict.get()

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cvpe** [comment]
Thanks
Often seen but I'm really not used with dict.get()
I'm also sure you could almost ameliorate each of my lines 😢

**Comment by cvpe** [comment]
It is not ok, you have to remove also line 99

**Comment by cclauss** [comment]
c'est vrai, je suis desole

**Comment by cvpe** [comment]
I never use github, only to share code, not to follow,modifications.
Thus, I've never made a pull request my self to modify my own code 😢

**Pull request merged**
