### PR TITLE
dict comprehension

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cvpe** [comment]
Hello
I'm sorry but that's the first time I use github and I don't know what I have to do in response to your mail.

**Comment by cclauss** [comment]
It looks like you figured out GitHub because the "merge" of my "pull request" seems to have worked perfectly.

Also, if you add [AddAfterAlarmToEvent.py](https://gist.github.com/cvpe/30c004fc0fc6a8b437c0dd86ae3eafa9) to this repo then I will send you a few pull requests on that code.  Pull requests can only be made on code in repos, _not_ on code in gists.

**Comment by cvpe** [comment]
Hi
Yes, I did find how to accept this merge.
But, I don't understand entirely this GitHub site.
I use the share tool of Pythonista to upload a script as Gist but
- how to add (move?) a script to a repo?
- do I need to delete the gist?
    - thus, I also need to update my links

I hope I'll not regret to share my scripts on GotHub because if I'm alone to use my scripts, I "accept" there aren't bug free, but if other people meet bugs in my script, I'll feel responsible.

Anyway, thanks for your very appreciated help.

**Comment by cvpe** [comment]
Ok, I've found how to upload a file to my repository but I need to first upload my script to Dropbox via the share tool in Pythonista.
Is there a way to upload directly from Pythonista to a repository?
Do I need to delete the gists of the same script?
Do I need to update the links in the Pythonista forum?

Sorry to ennoy you, but I promise (hum) to stop after these questions...

**Comment by cclauss** [comment]
I just copy from Pythonista and paste into the GitHub repo webpage.  Go into Pythonista and Select All, Copy the whole script.  Then go to the GitHub webpage and New File, click in the file content pane and Paste.  Give the file a name and Commit.  I use Dropbox for backup but I just.

You can delete the gists after you have the repo successfully created to to keep yourself and others from being confused.  You can edit (three dots (...) at the upper right) you Pythonista Forum post to point to your latest and greatest code.  There is nothing wrong with asking questions.  In fact, I believe that it is a best practice in life.

**Comment by cvpe** [comment]
Thanks a lot, surely for the initial advice (if somebody can use at least one of my scripts) but also for your help, and of course for your code modifications.

I've shared my 2nd code to Dropbox and then uploaded to GitHub via their upload file, then deleted from Dropbox. I'll also update my links in the forum.

You're right with your last sentence...

**Pull request merged**
