### PR TITLE
Add automated testing using Travis CI and flake8

### PR DESCRIPTION
**Pull request by cclauss**
To enable free automated testing of all code changes, you would need to:
1. go to https://travis-ci.com/cvpe
2. log in with GitHub credentials
3. select the __free plan__, and
4. flip the repository switch __on__.

When that is done, Travis CI will lint your Python code with http://flake8.pycqa.org

### CODE REVIEW

**Comment by cvpe** [comment]
Hello
Sorry, I don't understand anything 😢

**Comment by cclauss** [comment]
No problems.  Let's with the desired result...  Can you see this?
* https://travis-ci.com/cclauss/Pythonista-scripts-5/jobs/200375616#L463

That is __flake8__ finding "issues" with the Python code in this repo.  Hopefully that kinda insight would be of use.  If so, then try to do step 1 above and let me know if you can get that done or not.

If this kinda insight into code quality is not of interest then just close this pull request.

**Comment by cvpe** [comment]
I begin to understand (a little bit).
I'm going away for a 4-days holiday from tomorrow. Thus I'll leave that for when I come back.
Thanks
Christian

PS for  my personal curiosity, what is the signification, in your GitHubprofile, 
of "Organisations" 
               

Because, I have worked my-self 38 years at IBM...

**Comment by cclauss** [comment]
I have 930 days until retirement from IBM.  Yes.  I am counting them down with the help of Python.  I am also a "Contributor" to Node.js. etc.  My CV is https://www.linkedin.com/in/cclauss/

**Comment by cvpe** [comment]
when I stopped working, I've also removed my LinkedIn user thus I can't see your cv

**Comment by cclauss** [comment]
Bump on this one.

**Comment by cvpe** [comment]
Sorry, I don't understand.
Do you say that you work on it on that I have to work on it?
Be sure, I've not forgotten, your initial mail is alone in my 'not yet handled' mailbox.

**Comment by cclauss** [comment]
You need to go thru steps 1 to 4 above to turn the testing on.

**Comment by cvpe** [comment]
I understand that but I'm afraid I could receive thousands of modifications...and I really have not enough time nor pleasure to process them

**Comment by cclauss** [comment]
__--select=E9,F63,F72,F82__ is designed to focus only on a few errors that are really worth fixing.  Things like syntax errors, typos, and missing imports.

**Comment by cvpe** [comment]
3. select the free plan..................not seen
4.flip the repository switch on .....done of it is "activate"

**Comment by cclauss** [comment]
Nice — Click the red X below to see the issues to fix.  The first run of flake8 is the important one.  The second run can be ignored.

**Comment by cvpe** [comment]
Red x is not clickable

**Comment by cvpe** [comment]
Sorry, one more time, I don't understand, I feel "un peu bête" 😢
What that means and what do I have to do?

**Comment by cvpe** [comment]
Merged

**Comment by cclauss** [comment]
The four issues to fix are at https://travis-ci.com/cvpe/Pythonista-scripts

**Pull request merged**
