### PR TITLE
Travis CI: add flake8 E722 do not use bare 'except'

### PR DESCRIPTION
**Pull request by cclauss**
https://pep8.org/#programming-recommendations
https://realpython.com/the-most-diabolical-python-antipattern

$ __flake8 . --count --select=E722,E9,F63,F72,F82 --show-source --statistics__
```
./MyPickDocument.py:35:1: E722 do not use bare 'except'
except:
^
./SaveInFiles.py:25:1: E722 do not use bare 'except'
except:
^
./contacts on map.py:131:1: E722 do not use bare 'except'
except:
^
3     E722 do not use bare 'except'
3
```

### CODE REVIEW

**Comment by cvpe** [comment]
Sorry, I don't understand

**Comment by cclauss** [comment]
```python
try:
    do_something()
except:  # <-- this can hide bugs.  See the anti-pattern link above.
    pass
```

**Comment by cvpe** [comment]
I understand the code but I don't understand what I have to do...
Do I need to merge your pull request and/or manually modify my sources?
It is a very old code copied from omz, I think, when you create an ObjCClass

**Comment by cclauss** [comment]
Modify your sources.  Afterwards we can rerun these tests.

**Comment by cvpe** [comment]
Done

**Comment by cclauss** [comment]
On this page, can you rerun the tests?
https://travis-ci.com/cvpe/Pythonista-scripts/builds/135409234

**Comment by cclauss** [comment]
__Restart build__ on https://travis-ci.com/cvpe/Pythonista-scripts/builds/135409234

Are you on https://forum.omz-software.com/topic/3116/pythonista-slack-chat ?

**Comment by cvpe** [comment]
I'm not on slack-chat

**Comment by cclauss** [comment]
Go ahead and merge this one.  The tests will pass.

**Pull request merged**
